spring:
  datasource:
    url: jdbc:mysql://mysql2:3306/midzik_authentication_microservice?allowPublicKeyRetrieval=true&useSSL=false
    username: midzik_admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
